name: Builds (Windows, Linux, macOS)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    name: ${{ matrix.name }}-build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - name: windows-latest
            os: windows-latest
            config: win64
          - name: ubuntu-latest
            os: ubuntu-latest
            config: linux
          - name: macos-latest
            os: macos-latest
            config: macos

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: '3.x' # Semantic version range syntax or exact version of a Python version
        architecture: 'x64' # Optional - x64 or x86, defaults to x64

    - name: Clone dependencies
      run: |
        python fips fetch
        python fips set config ${{ matrix.config }}
        
    - name: Fix clang version
      if: startsWith(matrix.os, 'ubuntu')
      env:
        CC: clang-14
        CCX: clang++-14

    - name: Configure
      run: |
        python fips gen

    - name: Build
      run: |
        python fips build
