# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        name: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - name: windows-latest
            os: windows-latest
            config: win64
          - name: ubuntu-latest
            os: ubuntu-latest
            config: linux
          - name: macos-latest
            os: macos-latest
            config: macos

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.x
      uses: actions/setup-python@v3
      with:
        python-version: '3.x' # Semantic version range syntax or exact version of a Python version
        architecture: 'x64' # Optional - x64 or x86, defaults to x64

    - name: Clone dependencies
      run: |
        python fips fetch
        python fips set config ${{ matrix.config }}

    - name: Configure
      run: |
        python fips gen

    - name: Build
      run: |
        python fips build
